import './mypage.js?v=20260915-profile';
import {getApp} from 'https://www.gstatic.com/firebasejs/11.7.3/firebase-app.js';
import {getAuth,onAuthStateChanged} from 'https://www.gstatic.com/firebasejs/11.7.3/firebase-auth.js';
import {getFirestore,doc,getDoc} from 'https://www.gstatic.com/firebasejs/11.7.3/firebase-firestore.js';
import {getSavedPosts,toggleSavedPost} from './saved-posts.js?v=1';
const auth=getAuth(getApp()),db=getFirestore(getApp()),grid=document.getElementById('savedGrid');let user=null,generation=0;
function empty(title,description,href,label){grid.replaceChildren();const box=document.createElement('div');box.className='saved-empty';const heading=document.createElement('strong'),p=document.createElement('p');heading.textContent=title;p.textContent=description;box.append(heading,p);if(href){const a=document.createElement('a');a.href=href;a.textContent=label;box.append(a)}grid.append(box)}
function safeImage(data){const template=document.createElement('template');template.innerHTML=String(data.content||'');const src=String(data.thumbnailDataUrl||template.content.querySelector('img')?.getAttribute('src')||'');try{const u=new URL(src,location.href);return src&&(['https:','http:'].includes(u.protocol)||/^data:image\/(png|jpeg|webp|gif);base64,/.test(src))?u.href:''}catch{return ''}}
async function render(){const version=++generation;grid.replaceChildren();if(!user){document.getElementById('memberSavedCount').textContent='0';document.getElementById('savedTotal').textContent='0';empty('나만의 운동 컬렉션','로그인 후 게시글의 스크랩 버튼을 눌러 마음에 드는 글을 모아보세요.','login.html','로그인하기 ↗');return}let items;try{items=getSavedPosts(user.uid)}catch{empty('스크랩을 불러올 수 없습니다.','브라우저의 저장 공간 사용 설정을 확인해 주세요.');return}document.getElementById('memberSavedCount').textContent=items.length;document.getElementById('savedTotal').textContent=items.length;if(!items.length){empty('아직 스크랩한 글이 없어요.','마음에 드는 소식이나 운동 이야기를 저장해 보세요.','board.html?view=list','게시글 둘러보기 ↗');return}const snapshots=await Promise.allSettled(items.map(x=>getDoc(doc(db,'boards',x.id))));if(version!==generation)return;grid.replaceChildren();snapshots.forEach((result,i)=>{const item=items[i],data=result.status==='fulfilled'&&result.value.exists()?result.value.data():null,allowed=data&&!data.isSecret&&data.isPublic!==false&&!data.isAdminOnly&&!['infoboard','request'].includes(data.board)&&data.category!=='request';const card=document.createElement('article');card.className='saved-card';const a=document.createElement('a');a.href=allowed?'post.html?id='+encodeURIComponent(item.id):'board.html';const h=document.createElement('h2');h.textContent=allowed?(data.title||'제목 없음'):(result.status==='rejected'?'불러오지 못한 글':'삭제되었거나 볼 수 없는 글');if(allowed){const source=safeImage(data);if(source){const image=document.createElement('img');image.src=source;image.alt='';image.loading='lazy';a.append(image)}}a.append(h);const remove=document.createElement('button');remove.type='button';remove.textContent='−';remove.setAttribute('aria-label',(allowed?data.title:'게시글')+' 스크랩 해제');remove.addEventListener('click',()=>{try{toggleSavedPost(user.uid,item.id);render()}catch{remove.textContent='!';remove.setAttribute('aria-label','저장 공간 오류로 해제하지 못했습니다.')}});card.append(a,remove);grid.append(card)})}
onAuthStateChanged(auth,u=>{user=u;render()});addEventListener('storage',()=>render());addEventListener('pageshow',()=>{if(user)render()});
